upstream websocketoujili{
server 127.0.0.1:8089;
}

server {
    server_name oujiliapi.crget.com;
    location / {
		   proxy_pass http://127.0.0.1:8088/;
		   proxy_set_header Host $Host:$server_port; 
		   proxy_set_header X-Real-IP $remote_addr; 
		   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
		   proxy_set_header REMOTE-HOST $remote_addr; 
		   add_header X-Cache $upstream_cache_status; 
		   proxy_connect_timeout 30s; 
		   proxy_read_timeout 86400s; 
		   proxy_send_timeout 30s; 
		   proxy_http_version 1.1; 
		   proxy_set_header Upgrade $http_upgrade; 
		   proxy_set_header Connection "upgrade"; 
	  }

    location /wssoujili {
             proxy_pass http://websocketoujili/ws;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "Upgrade";
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/oujiliapi.crget.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/oujiliapi.crget.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = oujiliapi.crget.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name oujiliapi.crget.com;
    listen 80;
    return 404; # managed by Certbot


}